export default  function Head(){
    return (
        <>
        <title> About in the ABout page</title>
        <meta content="width=device-width, intial-scale=1" name="view"/>
        <meta name="description" content="Generated by About" />
        <link rel="stylesheet" href="/favicon.ico" />
        </>
    )
}